# Generated by Django 5.1.4 on 2024-12-10 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DogService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.IntegerField(choices=[(1, 'Kąpiel'), (2, 'Strzyżenie'), (3, 'Trymowanie'), (4, 'Mycie zębów'), (5, 'Podcinanie pazurów')], verbose_name='Nawza usługi')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Cena')),
            ],
        ),
        migrations.CreateModel(
            name='DogReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dog_name', models.CharField(max_length=64, verbose_name='Imię psa')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Numer telefonu właściciela')),
                ('comment', models.TextField(null=True, verbose_name='Komentarz')),
                ('reservation_time', models.DateTimeField(verbose_name='Czas rezerwacji')),
                ('status', models.CharField(choices=[('scheduled', 'Zaplanowana'), ('completed', 'Zakończona'), ('cancelled', 'Anulowana')], default='scheduled', max_length=20, verbose_name='Status')),
                ('services', models.ManyToManyField(related_name='dog_reservations', to='grooming.dogservice', verbose_name='Usługi')),
            ],
        ),
    ]
